---
title: 'Assignment 3: Almond Profit'
author: "Steven Cognac, Marie Rivers, Bri Baker"
date: "4/18/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(purrr)
library(patchwork)

```

# Read in Climate Data
```{r climate_data}
# import climate data hosted on Namoi Tague's github
clim <- read.csv(
  "https://raw.githubusercontent.com/naomitague/ESM232_Examples/main/Data/clim.txt", 
  sep = " ", header=TRUE)
```

## Run Almond Profit Model.

```{r}

# import function 
source(here("R", "almond_profit.R"))

# run function using climate data
almond_profits <- almond_profit(climate_data = clim)

```

# Sensitivity Analysis

```{r}
# generate samples for both parameters

deviation  <-  0.20
price <- 4000
acres <- 1600000

avg_cost <- runif(min = price - deviation * price, 
                max = price + deviation * price, n=100)

acres_used <- runif(min = acres - deviation * price, 
                    max = acres + deviation * price, n=100)

parms <- cbind.data.frame(avg_cost, acres_used)

# use pmap 
results <- parms %>% pmap(almond_profit,
                          climate_data = clim)

```

# Put into dataframe and clean

```{r clean_data}
 
annual_profit <- map_df(results,`[`, c("almond_profit",
                                       "almond_profit_anom",
                                       "year")) %>% 
  mutate(almond_profit_billion_dollar = (almond_profit/1000000000),
         almond_profit_anom_billion_dollar = (almond_profit_anom/1000000000))

annual_profit <- cbind.data.frame(annual_profit, parms)

```

```{r}
profit_plot <- ggplot(annual_profit, aes(x = as.factor(year), 
                                       y = almond_profit_billion_dollar, 
                                       group = year))+
  geom_boxplot() +
  labs(y = "Profit (Billion Dollars)", 
       x = "Year", 
       title = "Sensitivity Analysis of Almond Profit in California",
       subtitle = "Parameters varied include 'acre' and 'cost'",
       caption = "Average almond yield, price and acreage source:\n https://fruitgrowers.com/california-almond-production-is-booming/ \n https://www.almonds.com/sites/default/files/2021-04/2020%20Acreage%20Report.pdf") +
  theme(plot.caption = element_text(hjust = -0.2), plot.caption.position = "plot") +
  scale_x_discrete(breaks = seq(1989,2010, by = 2)) +
  theme_minimal()

profit_plot
```


# Summary of results

```{r}
# ggsave(here("figs/profit_plot.jpg"), plot = profit_plot)
```

